### ISSUE TITLE
ADCS MCU - Meet with OBC to discover past STM32 chip design work

### ISSUE THREAD

**Issue by Aidan-Sheedy** [queens-satellite-team/adcs#26]
# Motivation/Description ⛰️ 
OBC has already worked with STM32 chips in the past. To save time and effort, we should collaborate with them to see if we can leverage their past design work.

# Next Steps 🚶 
- [x] Consult with @jillianmalherbe as to what design work has been done on STM32
- [x] If possible, see what changes would need to be made to adapt the design work for the ADCS MCU
- [x] Create a document outlining the past design work, necessary changes, and future questions about the design that need solving. 
- [x] Create a space in the ADCS teams channel to copy all available documentation for the old OBC design
- [x] Create tickets for changes to the design and future questions/problems with it.

# Supporting Material and Resources 📖 
- [OBC V1 Documentation](https://queensuca.sharepoint.com/:w:/r/teams/GROUP-QSET/Shared%20Documents/Satellite-OBC/OBC%202021-2022/OBC%20V1%20Documentation.docx?d=wbe27c4fe86f64b30a6ad24559bc99bfa&csf=1&web=1&e=lxc1gt)
- [OBC STM32 PCB Design](https://github.com/queens-satellite-team/pcbs/tree/master/OBC_Boards/STM32_Breakout)
- [ADCS MCU Documentation](https://queensuca.sharepoint.com/:w:/r/teams/GROUP-QSET/Shared%20Documents/Satellite-General/csdc/4000-systems-design/csdc-4100-adcs-design/csdc-4100-adcs-mcu-design.docx?d=w1d5f520a2ecb4909be88e1ae474b04e9&csf=1&web=1&e=luVCBC)

# Definition of Done 💯 
This task is done when the above document has been created and tickets are created changes needed to the MCU design, and the old documentation has been copied to the ADCS teams channel.

### Tags
> tag people that should know about this issue

cc: @SeanTedesco @emmapaczkowski @Aidan-Sheedy @jillianmalherbe

**Comment by Aidan-Sheedy** [comment]
From @jillianmalherbe about past STM32 designs:

>"If you look the the teams GitHub in the “pcbs” repository, you can find our KiCad files. I think ours is called “STM32Breakout” "

**Comment by Aidan-Sheedy** [comment]
Further questions for OBC:
1. Does ADCS need to keep track of temperature?
2. What is necessity of having SRAM and Micro SD slot?
3. What is the difference between the Real time clock and the "Duplicate crystal oscillator"?
4. How much more of the design can be reduced to fit ADCS requirements?

**Comment by SeanTedesco** [comment]
Hey @Aidan-Sheedy, adding in to the above questions:

1. Systems should be able to collect telemetry for their own system. The motivation behind this is it allows for more flexibility and reusability for the individual sub-systems - these being overarching goals for all our designs. That being said, the EPS is quite fancy and can monitor the input voltage and current of most systems. I am suggesting that if a sub-system must generate its own power rails, then it must also collect telemetry on them as well. 

2. I am not sure of the benefits of this design decision. Going forward, I think the OBC should be simplified to only have 1x  external memory storage that is long-term and non-volatile, and 1x to hold the operating system - which can be the SD card used in the RPi-4. @jillianmalherbe I believe that is what we are going with currently?

4. If I understand correctly, I believe the design of the OBC v1 uses a total of 2x crystal oscillators: 1x for the MCU and 1x for the RTC. So the "duplicate crystal oscillator" just means that there is a crystal oscillator used in the circuit to control the real-time clock that is separate from the one used in the MCU circuit.

5. This could be a large discussion; let's schedule a meeting to determine ADCS requirements. It will be good to have OBC team there as well. 

And for reference, here is the link to the OBC documentation mentioned above: 
- https://queensuca.sharepoint.com/:w:/t/GROUP-QSET/Ef7EJ772hjBLpq0kVZvJm_oBxgv2ckS-2uk7wlKNyAkHAg?e=J7Rz2n

**Comment by Aidan-Sheedy** [comment]
Thanks @SeanTedesco,

I agree we need to have a meeting - let's wait for full meetings to start so we can include general members working on the project.

**Comment by Aidan-Sheedy** [comment]
The MCU design has been mostly finalized at a high level. The documentation is here: (adcs-1001-mcu-hardware-design.docx)[https://queensuca.sharepoint.com/:w:/r/teams/GROUP-QSET/Shared%20Documents/Satellite-ADCS/adcs-1000-documentation/adcs-1000-subsystem-design-documents/[adcs-1001-mcu-hardware-design.docx](https://queensuca.sharepoint.com/:w:/r/teams/GROUP-QSET/Shared%20Documents/Satellite-ADCS/adcs-1000-documentation/adcs-1000-subsystem-design-documents/adcs-1001-mcu-hardware-design.docx?d=wd0317a3c7d3840a2b2b37d21e9574179&csf=1&web=1&e=ya1eCh)?d=wd0317a3c7d3840a2b2b37d21e9574179&csf=1&web=1&e=ya1eCh]
